// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1tMD0Y71hyZB-Q-P9orqysRGTW5gD44U',
    appId: '1:72789050659:web:2179c44a6599b57495f896',
    messagingSenderId: '72789050659',
    projectId: 'wouri-tv-f3c47',
    authDomain: 'wouri-tv-f3c47.firebaseapp.com',
    storageBucket: 'wouri-tv-f3c47.firebasestorage.app',
    measurementId: 'G-CGR82YGPND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUBvSwhDnDIej_DXOiA9jqpcRIwNi7MWY',
    appId: '1:72789050659:android:36ba2694a61d909795f896',
    messagingSenderId: '72789050659',
    projectId: 'wouri-tv-f3c47',
    storageBucket: 'wouri-tv-f3c47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR-XqcpNc3RVsQQ8_9WN7Vc0KGy6W40u8',
    appId: '1:72789050659:ios:ac1bd9b0b2ba4a2095f896',
    messagingSenderId: '72789050659',
    projectId: 'wouri-tv-f3c47',
    storageBucket: 'wouri-tv-f3c47.firebasestorage.app',
    iosClientId: '72789050659-8h2t7laml3ko5m8mrod586aa7vkm6s5p.apps.googleusercontent.com',
    iosBundleId: 'ios.apps.wouri.tv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR-XqcpNc3RVsQQ8_9WN7Vc0KGy6W40u8',
    appId: '1:72789050659:ios:1ecc0db1aa32a18595f896',
    messagingSenderId: '72789050659',
    projectId: 'wouri-tv-f3c47',
    storageBucket: 'wouri-tv-f3c47.firebasestorage.app',
    iosBundleId: 'com.example.wouritv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiKC05OJPkRm2Dqyy5W-KtALwJxB2ZKoM',
    appId: '1:72789050659:web:d0d2260cca748b1395f896',
    messagingSenderId: '72789050659',
    projectId: 'wouri-tv-f3c47',
    authDomain: 'wouri-tv-f3c47.firebaseapp.com',
    storageBucket: 'wouri-tv-f3c47.firebasestorage.app',
    measurementId: 'G-R08K8BV0P2',
  );
}
